# Generated by Django 5.0.4 on 2024-04-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0003_remove_user_posts_post_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="users",
            new_name="user",
        ),
    ]
