# Generated by Django 5.0.4 on 2024-04-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0008_alter_user_options_alter_user_managers_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
