# Generated by Django 5.0.4 on 2024-04-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "social_network",
            "0009_alter_comment_created_at_alter_post_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(verbose_name="Senha"),
        ),
    ]
