# Generated by Django 5.0.4 on 2024-04-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0012_alter_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email do Usuário"
            ),
        ),
    ]
