# Generated by Django 5.0.4 on 2024-04-29 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0014_alter_comment_created_at_alter_comment_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Seguidores",
            ),
        ),
    ]
