version: '3.9'

services:
  django:
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py makemigrations --no-input && python manage.py migrate && \ python manage.py await_for_db && python manage.py runserver 0.0.0.0:8000"
    build:
      args:
        - DEV=true
      context: .
    env_file: ./dotenv-files/.env
    depends_on:
      - postgres

  postgres:
    ports:
      - "5431:5432"
    image: postgres:16-alpine
    volumes:
      - dev-db:/var/lib/postgresql/data/
    env_file: ./dotenv-files/.env

volumes:
  dev-db:


