# Generated by Django 5.0.4 on 2024-04-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_network", "0004_rename_users_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(blank=True, related_name="Followed", to="social_network.user"),
        ),
    ]
